pipeline{
agent any
environment{
         DOCKERHUB_PASS = credentials('akhpngubuntu')
         }
         stages{
         stage("Building the Student survey"){
         steps{
         script{
         checkout scm
         sh 'rm -rf *.war'
         sh 'jar -cvf index.war -C WebContent/ .'
         sh ' echo ${BUILD_TIMESTAMP}'
         sh "docker login -u akhpng31 -p ${DOCKERHUB_PASS}"
         def customImage = docker.build("akhpng31/phani645:${1000}")
         }
         }
         }
         stage("pushing image"){
         steps{
         script{
         sh 'docker push akhpng31/phani645:${1000}'
         }
         }
         }
         stage("Deploying to rancher as pod"){
         steps{
         sh 'kubectl set image deployment/stusurvey-pipeline stusurvey-pipeline=akhpng31/phani645:${BUILD_TIMESTAMP} -n jenkins-pipeline'
         }
         }
         stage("Deploying to rancher with load balancer")
         {
         steps{
         sh 'kubectl set image deployment/phani645-lb phani645-lb=akhpng31/phani645:${BUILD_TIMESTAMP} -n jenkins-pipeline'
         }
         }
         }
         }