pipeline{

environment{
           registry = "akhpng31/phani645"
  registryCredential = "dockerhub"
         del datelog = new Date().format("yyyyMMdd : HHmmss")
         }
agent any
  stages{
         stage("Building the Student war"){
         steps{
         script{
         
         sh 'rm -rf *.war'
         sh 'jar -cvf index.war -C src/main/webapp .'
         docker.withRegistry('',registryCredential){
         def img = docker.build("akhpng31/phani645:"+ dateTag)
         }
         }
         }
         }

  
         stage("pushing latest code to docker hub"){
         steps{
         script{
             docker.withRegistry('', registryCredential){
             del image docker.build("akhpng31/phani645:"+ datelog, " . --no cache")
             docker.withRegistry('',registryCredential){
                      image.push()
                  
         }
         }
         }
         }
         }
         stage("Deploying to rancher as pod"){
         steps{
         script{
         sh 'kubectl set image deployment/dp container-0=akhpng31/phani645:'+ dateTag
         sh 'kubectl set image deployment/dplb container-0=akhpng31/phani645:'+ dateTag
         }
         }
         }
         }
post{
         always{
                  sh 'docker logout'
         }
}
}
