apiVersion: v1
kind: Config
clusters:
- name: "swe645"
  cluster:
    server: "https://34.237.189.184/k8s/clusters/c-m-dp7d72nm"
    certificate-authority-data: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJ2RENDQ\
      VdPZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQkdNUnd3R2dZRFZRUUtFeE5rZVc1aGJXbGoKY\
      kdsemRHVnVaWEl0YjNKbk1TWXdKQVlEVlFRRERCMWtlVzVoYldsamJHbHpkR1Z1WlhJdFkyRkFNV\
      Fk1T0RFNQpOelE0TkRBZUZ3MHlNekV3TWpVd01UTXhNalJhRncwek16RXdNakl3TVRNeE1qUmFNR\
      Vl4SERBYUJnTlZCQW9UCkUyUjVibUZ0YVdOc2FYTjBaVzVsY2kxdmNtY3hKakFrQmdOVkJBTU1IV\
      1I1Ym1GdGFXTnNhWE4wWlc1bGNpMWoKWVVBeE5qazRNVGszTkRnME1Ga3dFd1lIS29aSXpqMENBU\
      VlJS29aSXpqMERBUWNEUWdBRXV4b1FRbDRhTVFrcQpBTllWcDRnYXIycjk5UkV4Mm9OampqVlhoO\
      HdYTmQ5bk9QRjcvd3BnZHNUZGx0SE5GYjcwN1FVRmxmSXBJbStiCnhYNmlBWG00TktOQ01FQXdEZ\
      1lEVlIwUEFRSC9CQVFEQWdLa01BOEdBMVVkRXdFQi93UUZNQU1CQWY4d0hRWUQKVlIwT0JCWUVGS\
      zBxK1NFL0cxYkxiUnJnODFnaTNPS1RldjVBTUFvR0NDcUdTTTQ5QkFNQ0EwY0FNRVFDSUVqdwpKR\
      Hh5ZkwyWE1TOU96cVFLVlFST21UT0FNaG1sTWVWOUVZd3BFQkRvQWlBNnFUS21CM1lHclRNRHViS\
      TZKOU9oCks1TFRCajl1UnpWSW9NTDFxRFkrdHc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0t"

users:
- name: "swe645"
  user:
    token: "kubeconfig-user-kv292d9wkf:4tnf6cjqsmg7twqfqd4m7gswqk5tl7ngzhkqgvfvkghzmbhmcwz5xx"


contexts:
- name: "swe645"
  context:
    user: "swe645"
    cluster: "swe645"

current-context: "swe645"
